spring:
  batch:
    initializer:
      enabled: true
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    continueOnError: false
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    initialization-mode: embedded
    platform: h2
    username: sa
    password:
    data: classpath=data.sql

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      gerate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
